version: '2'
volumes:
  redis-data:
    external: true
    driver: rancher-nfs
  postgresql-data:
    external: true
    driver: rancher-nfs
  gitlab-data:
    external: true
    driver: rancher-nfs
services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      '- DB_EXTENSION': pg_trgm
      '- DB_NAME': gitlabhq_production
      '- DB_PASS': password
      '- DB_USER': gitlab
    stdin_open: true
    volumes:
    - postgresql-data:/var/lib/postgresql:Z
    tty: true
    labels:
      io.rancher.container.pull_image: always
  gitlab:
    image: sameersbn/gitlab:10.5.1
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_NAME: gitlabhq_production
      DB_PASS: password
      DB_PORT: '5432'
      DB_USER: gitlab
      DEBUG: 'false'
      GITLAB_BACKUP_SCHEDULE: daily
      GITLAB_BACKUP_TIME: 01:00
      GITLAB_EMAIL: *@*.cn
      GITLAB_EMAIL_FROM: *@*.cn
      GITLAB_EMAIL_REPLY_TO: *@*.cnm
      GITLAB_HOST: *.cn
      GITLAB_HTTPS: 'false'
      GITLAB_INCOMING_EMAIL_ADDRESS: *@*.cnm
      GITLAB_NOTIFY_ON_BROKEN_BUILDS: 'true'
      GITLAB_NOTIFY_PUSHER: 'false'
      GITLAB_PORT: '80'
      GITLAB_RELATIVE_URL_ROOT: ''
      GITLAB_ROOT_EMAIL: *@*.cn
      GITLAB_ROOT_PASSWORD: Abcd=5757
      GITLAB_SECRETS_DB_KEY_BASE: *
      GITLAB_SECRETS_OTP_KEY_BASE: *
      GITLAB_SECRETS_SECRET_KEY_BASE: *
      GITLAB_SSH_PORT: '10022'
      GITLAB_TIMEZONE: Beijing
      IMAP_ENABLED: 'false'
      IMAP_HOST: imap.exmail.qq.com
      IMAP_PASS: *
      IMAP_PORT: '993'
      IMAP_SSL: 'true'
      IMAP_STARTTLS: 'true'
      IMAP_USER: gitlab@*.cn
      OAUTH_ALLOW_SSO: ''
      OAUTH_AUTH0_CLIENT_ID: ''
      OAUTH_AUTH0_CLIENT_SECRET: ''
      OAUTH_AUTH0_DOMAIN: ''
      OAUTH_AUTO_LINK_LDAP_USER: 'false'
      OAUTH_AUTO_LINK_SAML_USER: 'false'
      OAUTH_AUTO_SIGN_IN_WITH_PROVIDER: ''
      OAUTH_AZURE_API_KEY: ''
      OAUTH_AZURE_API_SECRET: ''
      OAUTH_AZURE_TENANT_ID: ''
      OAUTH_BITBUCKET_API_KEY: ''
      OAUTH_BITBUCKET_APP_SECRET: ''
      OAUTH_BLOCK_AUTO_CREATED_USERS: 'true'
      OAUTH_CAS3_DISABLE_SSL_VERIFICATION: 'false'
      OAUTH_CAS3_LABEL: cas3
      OAUTH_CAS3_LOGIN_URL: /cas/login
      OAUTH_CAS3_LOGOUT_URL: /cas/logout
      OAUTH_CAS3_SERVER: ''
      OAUTH_CAS3_VALIDATE_URL: /cas/p3/serviceValidate
      OAUTH_CROWD_APP_NAME: ''
      OAUTH_CROWD_APP_PASSWORD: ''
      OAUTH_CROWD_SERVER_URL: ''
      OAUTH_ENABLED: 'false'
      OAUTH_EXTERNAL_PROVIDERS: ''
      OAUTH_FACEBOOK_API_KEY: ''
      OAUTH_FACEBOOK_APP_SECRET: ''
      OAUTH_GITHUB_API_KEY: ''
      OAUTH_GITHUB_APP_SECRET: ''
      OAUTH_GITHUB_URL: ''
      OAUTH_GITHUB_VERIFY_SSL: ''
      OAUTH_GITLAB_API_KEY: ''
      OAUTH_GITLAB_APP_SECRET: ''
      OAUTH_GOOGLE_API_KEY: ''
      OAUTH_GOOGLE_APP_SECRET: ''
      OAUTH_GOOGLE_RESTRICT_DOMAIN: ''
      OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL: ''
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL: ''
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME: ''
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME: ''
      OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME: ''
      OAUTH_SAML_EXTERNAL_GROUPS: ''
      OAUTH_SAML_GROUPS_ATTRIBUTE: ''
      OAUTH_SAML_IDP_CERT_FINGERPRINT: ''
      OAUTH_SAML_IDP_SSO_TARGET_URL: ''
      OAUTH_SAML_ISSUER: ''
      OAUTH_SAML_LABEL: '"Our SAML Provider"'
      OAUTH_SAML_NAME_IDENTIFIER_FORMAT: urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      OAUTH_TWITTER_API_KEY: ''
      OAUTH_TWITTER_APP_SECRET: ''
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SMTP_AUTHENTICATION: login
      SMTP_ENABLED: 'true'
      SMTP_HOST: smtp.exmail.qq.com
      SMTP_PASS: *
      SMTP_PORT: '465'
      SMTP_STARTTLS: 'true'
      SMTP_TLS: 'true'
      SMTP_USER: gitlab@*.cn
      SSL_SELF_SIGNED: 'false'
      TZ: Asia/Shanghai
      UNICORN_TIMEOUT: '300'
    stdin_open: true
    volumes:
    - gitlab-data:/home/git/data:Z
    tty: true
    links:
    - redis:redis
    - postgresql:postgresql
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_soft_ne: server=server
  redis:
    image: sameersbn/redis:latest
    stdin_open: true
    volumes:
    - redis-data:/var/lib/redis:Z
    tty: true
    command:
    - --loglevel
    - warning
    labels:
      io.rancher.container.pull_image: always
